version: '3'
services:
  presentation:
    image: nginx:alpine
    ports:
    - 9000:80
    volumes:
    - .:/usr/share/nginx/html
    stdin_open: true
    container_name: docker-presentation