version: '3'
services:
  grocery-app:
    volumes:
    - ./GroceryApp/dist:/etc/nginx/html
    - ./GroceryApp/nginx.conf:/etc/nginx/nginx.conf
    - ~/.ssl:/ssl
    image: nginx:alpine
    container_name: grocery-app
    stdin_open: true
    ports:
    - "8080:80"

  banana-service:
    volumes:
    - ./BananaService:/service
    image: microsoft/aspnetcore-build
    container_name: banana-service
    stdin_open: true
    working_dir: /service
    ports:
    - "8081:80"
    command: dotnet run

  potato-service:
    volumes:
    - ./PotatoService:/go
    image: golang:alpine
    container_name: potato-service
    stdin_open: true
    ports:
    - "8082:9090"
    command: bin/potato-service

  grocery-app-tests:
    volumes:
    - ./GroceryApp:/project
    image: node:alpine
    container_name: grocery-app-tests
    stdin_open: true
    working_dir: /project
    command: npm run test:watch
    environment:
    - SHELL=/bin/sh

  grocery-app-build:
    volumes:
    - ./GroceryApp:/project
    image: node:alpine
    container_name: grocery-app-build
    stdin_open: true
    working_dir: /project
    command: npm run build:watch